name: generate-aowow-database
on:
  workflow_dispatch:

jobs:
  generate-aowow-db:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: "run scripts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/azerothcore/acore-docker
          cd acore-docker
          docker compose up -d

          cd ../setup/

          bash generate-db.sh

          cd ..

          revision=`mysql -u root -ppassword -P 63306 -h 127.0.0.1 -s -N -e "SELECT substring_index(substring_index(revision, 'rev. ', -1), '+ 2', 1)  FROM acore_auth.uptime ORDER BY starttime DESC LIMIT 1;"`
          release_name=$(date '+%Y-%m-%d_%H-%M-%S')
          gh release create $release_name --title "$release_name" --notes "Revision: [$revision](https://github.com/azerothcore/azerothcore-wotlk/commit/$revision)"
          gh release upload $release_name "aowow_db.sql.zip"
